# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(20, 40, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(60, 40, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.textBrowser_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_log.setGeometry(QtCore.QRect(410, 40, 651, 791))
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.label_log = QtWidgets.QLabel(self.centralwidget)
        self.label_log.setGeometry(QtCore.QRect(410, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_log.setFont(font)
        self.label_log.setObjectName("label_log")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(40, 760, 48, 48))
        self.pushButton_start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-start-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon)
        self.pushButton_start.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_start.setAutoDefault(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(170, 760, 48, 48))
        self.pushButton_stop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons8-stop-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon1)
        self.pushButton_stop.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(310, 760, 48, 48))
        self.pushButton_quit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons8-export-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_quit.setIcon(icon2)
        self.pushButton_quit.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.label_filter = QtWidgets.QLabel(self.centralwidget)
        self.label_filter.setGeometry(QtCore.QRect(20, 90, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_filter.setFont(font)
        self.label_filter.setObjectName("label_filter")
        self.comboBox_reviewer = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_reviewer.setGeometry(QtCore.QRect(130, 150, 181, 21))
        self.comboBox_reviewer.setEditable(False)
        self.comboBox_reviewer.setObjectName("comboBox_reviewer")
        self.label_reviewer = QtWidgets.QLabel(self.centralwidget)
        self.label_reviewer.setGeometry(QtCore.QRect(20, 150, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_reviewer.setFont(font)
        self.label_reviewer.setObjectName("label_reviewer")
        self.checkBox_5star = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5star.setGeometry(QtCore.QRect(130, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.checkBox_5star.setFont(font)
        self.checkBox_5star.setChecked(True)
        self.checkBox_5star.setObjectName("checkBox_5star")
        self.label_star = QtWidgets.QLabel(self.centralwidget)
        self.label_star.setGeometry(QtCore.QRect(20, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_star.setFont(font)
        self.label_star.setObjectName("label_star")
        self.checkBox_4star = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4star.setGeometry(QtCore.QRect(130, 240, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.checkBox_4star.setFont(font)
        self.checkBox_4star.setChecked(True)
        self.checkBox_4star.setObjectName("checkBox_4star")
        self.checkBox_3star = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3star.setGeometry(QtCore.QRect(130, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.checkBox_3star.setFont(font)
        self.checkBox_3star.setChecked(True)
        self.checkBox_3star.setObjectName("checkBox_3star")
        self.checkBox_2star = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2star.setGeometry(QtCore.QRect(130, 320, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.checkBox_2star.setFont(font)
        self.checkBox_2star.setChecked(True)
        self.checkBox_2star.setObjectName("checkBox_2star")
        self.checkBox_1star = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1star.setGeometry(QtCore.QRect(130, 360, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.checkBox_1star.setFont(font)
        self.checkBox_1star.setChecked(True)
        self.checkBox_1star.setObjectName("checkBox_1star")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_id.setText(_translate("MainWindow", "ID:"))
        self.label_log.setText(_translate("MainWindow", "Log Window:"))
        self.label_filter.setText(_translate("MainWindow", "Filter:"))
        self.label_reviewer.setText(_translate("MainWindow", "Reviewer:"))
        self.checkBox_5star.setText(_translate("MainWindow", "5 star"))
        self.label_star.setText(_translate("MainWindow", "Star:"))
        self.checkBox_4star.setText(_translate("MainWindow", "4 star"))
        self.checkBox_3star.setText(_translate("MainWindow", "3 star"))
        self.checkBox_2star.setText(_translate("MainWindow", "2 star"))
        self.checkBox_1star.setText(_translate("MainWindow", "1 star"))
